### ISSUE TITLE
Enhancement: Combine multiple lists "Merged-Lists"

### ISSUE THREAD

**Issue by spec1re** [jjssoftware/m3u-epg-editor#15]
I think this could be a very useful feature, eg. the Kodi IPTV-Simple-Client add-on can only handle one m3u/epg list.

So download few lists merge them and process or download few lists, have different sets of rules for each to process and merge them afterwards to one file. I don't know which one makes more sense. 

Thanks. :)

**Comment by jjssoftware** [comment]
It is kinda nice but complexity could snowball with this feature depending on it is implemented and there are a few things that will need to be thought through. 

The most simple way to implement this feature would be the shared rules / arguments for all m3us.

The most flexible way to implement this would probably be with separate rules / arguments per m3u. That said it might make sense for `--sortchannels / -s` to be applied after all m3us are downloaded and filtered to groups / channels. In other words it might make sense for there to be a single desired sort order that gets applied to all channels (if sort order is specified).

One thing that I think is worth mentioning is that this idea is likely not going to work at all with CLI arguments if we were to go for separate rules per m3u option. The reason being is that there's a limit to the number / length of arguments that can be passed at the command line. Different operating systems have their own specific limitations in this area and the volume of arguments that will need to be passed is probably going to increase by a factor of 2 with this feature (at least 2 - it will be depend on the number of configurations). I imagine this would work fine with the `--json_cfg / -j` JSON configuration file option however if the JSON was restructured to support an array of configs.

Lastly I imagine that each m3u file configured would be paired with an epg file since a given provider can supply their own epg (of varying quality) intended for use with their m3u. Doing it this way would probably be the best hope of achieving a semi-usable merged epg for all merged m3us.
