### ISSUE TITLE
Feature Request: Keep Channels

### ISSUE THREAD

**Issue by specsnow** [jjssoftware/m3u-epg-editor#29]
I know that you can remove specific channels using -c but it would be nice if you could instead keep specific channels in a specific group. 

For example, I have an M3U that has 3 categories: USA, UK, US REGIONALS. I know that if I do:
-g="'USA','US REGIONALS'"
I will get all the US channels and not the UK ones. But what if I want just a handful of the US REGIONALS channels? Today I'd have to add -c and try to define all the channels I want removed, but it would be much easier to define the ones I wanted to keep specific to that group instead, in this particular example.

**Comment by jjssoftware** [comment]
I might take a look at implementing this at some point. On the face of it, this could work via the introduction of a new argument that describes how the -c argument should work i.e. exclude (the default behaviour) as it currently works today and include as you would like it to work for this new feature.

**Comment by jjssoftware** [comment]
Ok, interesting. That idea presents some challenges that would need to be thought through or at least agreed on before embarking on an implementation:

1. Which argument "wins" in order of precedence would need to be decided. In other words when both the existing `-c` channel exclusion argument and the new channel within a group channel inclusion argument are specified, would the desired / expected behaviour be for the `-c` channel exclusion argument to always work regardless of the new channel inclusion argument or should a channel be included even though it did actually match a channel that would normally be excluded via the `-c / --channels` argument.
2. It would appear as though this new feature suggestion could be described with an argument that looks like an array of tuples where the first value in a given tuple is the name of a group and the second value in that same given tuple is the name of a channel to keep within the associated group. If this visualization of the feature is correct, modelling the new argument in this way could work for both command line argument users and also `-j / --json_cfg` json config file users. That said configuration of this argument might get a bit unwieldy / wordy quite quickly.
3. One thing that would need to be considered is that there is a limit to the number / length of arguments that can be passed at the command line and different operating systems have their own specific limitations in this area. With that in mind, this might be a feature that can only reasonably be modelled / configured in json configuration.

**Comment by jjssoftware** [comment]
Thinking about this some more, I think it's reasonable to assume that a given channel only ever exists solely within one single group in any m3u file. With that in mind, perhaps this feature simply needs to be implemented as a new include channels argument (an array of channel names) in addition to the existing `-c / --channels` exclude channels argument. 

If this is correct, both the configuration and implementation will be simplified and the configuration will not be as unwieldy as the array of tuples idea previously mentioned.

If we can agree on this as an idea, we'll only need to iron out how item (1) that was mentioned in the previous comment needs to work to clear the path for this feature.

Let me know what you think.

**Comment by jjssoftware** [comment]
The plan:

1. Rename the existing `-c / --channels` argument to `-dc / --discard_channels`
2. Introduce a new `-ic / --include_channels` argument
3. The new `-ic / --include_channels` argument will describe an array of channel names that will **always** be kept regardless of whether a given channel in the `-ic` array is specified in the `-dc` array or whether that given channel is in a kept or discarded group. In other words, the  new `-ic / --include_channels` argument will describe an array of channel names that will always be hard kept, effectively overriding any other group or channel configuration.

I'll leave this here for a while for further discussion / comments before making the change.

**Comment by specsnow** [comment]
This implementation makes sense and looks great. The only thing it's missing in my opinion is the ability to specify which group specifically the -ic argument should apply to. If it needs to apply to the entire list then it's definitely better than nothing but being able to specify a specific group or groups would be ideal. Maybe like: 
"-ic [(group1:keep1, keep2), (group2:keep3, keep4)]"

**Comment by jjssoftware** [comment]
I might be missing something because I'm stuck in the mindset of what I mentioned in this earlier comment at the moment: https://github.com/jjssoftware/m3u-epg-editor/issues/29#issuecomment-525441815. It seems that being able to describe the group that a channel is in with the `-ic` argument might not be required.

Can you explain why being able to specify which group the channels in the `-ic` argument apply to would be useful?

**Comment by boredness** [comment]
I was coming back here looking to see if there was a command to remove certain channels and this is basically exactly what i was looking for.
1+

**Comment by jjssoftware** [comment]
Implemented as originally described in [this comment](https://github.com/jjssoftware/m3u-epg-editor/issues/29#issuecomment-530255202) in https://github.com/jjssoftware/m3u-epg-editor/commit/0167056370dba5f39bf4723262b7908993eab340

Other ideas were not described well enough to make a strong case for implementation.

**Comment by sabre6** [comment]
thank you.  to be clear, do we need to name all channels in the m3u to keep?  Or, can we name certain groups to keep (actually discard in my case, and keep all the other groups), and within a group, tell it what channels to keep (discard the rest)?

**Comment by jjssoftware** [comment]
It's not you @sabre6, it looks like a bug. I'll fix asap.

**Comment by jjssoftware** [comment]
Hopefully this should sort it out: https://github.com/jjssoftware/m3u-epg-editor/commit/fd91b8575c641e3bafeecba3c763c1a1a1f09ee6

**Comment by sabre6** [comment]
> Hopefully this should sort it out: [fd91b85](https://github.com/jjssoftware/m3u-epg-editor/commit/fd91b8575c641e3bafeecba3c763c1a1a1f09ee6)

fantastic, all good. thanks!
