### ISSUE TITLE
Feature Request: Exclude certain groups

### ISSUE THREAD

**Issue by sabre6** [jjssoftware/m3u-epg-editor#30]
Hi, just throwing this out.  I have a source that keeps moving around group names/options.  I know i want to exclude certain groups all the time, but as i dont know what will be added, would like to keep those (albeit, i dont have the name for the script) until i can take a look.  So, instead of saying what group we would like to keep in your great script, is it possible to say what groups we want to EXCLUDE - and keep all the rest?  

Thank you

**Comment by jjssoftware** [comment]
Being able to exclude specific groups rather than include specific groups (as the script currently works) is a valid feature request.

That said I must admit that I don't quite understand how this solves the problem that you have described.

At present the configuration / argument values passed to this script are deterministic in so far as the script can be trusted to work reasonably well when the m3u data that it processes is reasonably stable. The thing that I'm struggling with is that if an m3u source can be trusted to move and change group names randomly, I can envisage a situation where excluding specific groups could be just as error prone / problematic as including specific groups.

There is no artificial intelligence here and there won't ever be any (in this fork at least ;) ) If you can live with that and you think that being able to exclude groups rather than include them will somehow make this work better for you, I'd be happy to implement some sort of polarity switcher on the `-g / --groups` argument.

**Comment by sabre6** [comment]
Yes, good points, and I totally understand.  I know this could introduce groups that I do not want.  But I was thinking of being conservative and introduce all new groups that i did not expect, then i would not miss anything. And seeing a group added that i then do not want, i can exclude it going forward.  

It really works great for me now, so it is more a luxury than requirement. If it adds complication or a lot of added time, then please do pass on it.

**Comment by jjssoftware** [comment]
This isn't a huge ask tbh and I decided to implement on the basis that it sounds like it's going to work for you and I think it's a worthwhile feature beyond that use-case that you described.

https://github.com/jjssoftware/m3u-epg-editor/commit/3344e5589cb25ee603be32923faffaf733ee4c3c should do it.

A new argument called `-gm / --groupmode` has been introduced that supports "keep" and "discard" values that enable you to specify how you want the `-g / --groups` argument to work. By default `-g / --groups` will continue to work in "keep / include" mode, but it can be switched into "discard / exclude" mode with the `-gm / --groupmode` "discard" value.

Give it a whirl and let me know if you see any issues.

**Comment by sabre6** [comment]
Works like a charm, thank you!
