### ISSUE TITLE
What happens when no group specified?

### ISSUE THREAD

**Issue by sabre6** [jjssoftware/m3u-epg-editor#31]
Hi, I am seeing an issue, where some channels in a list do not have a group name.  In the .m3u, group will show as "".  Yes, they should have a group and probably will at some point, but right now the editor does not seem to pick them up (ie, if i discard some groups, and then leave all the rest). Also does not show them on the "original.channels.txt."  Any ideas on this?  Thanks again.

**Comment by jjssoftware** [comment]
Hi there, I've not tested this scenario but I expect that it's this:

https://github.com/jjssoftware/m3u-epg-editor/blob/master/m3u-epg-editor.py#L62

As can be seen on this line of code, a parsed channel from the original m3u file is currently considered invalid and is effectively thrown away when that channel has no group-title attribute or the group-title attribute does exist but it's value is empty / contains nothing. 

The reason that a channel that has no group isn't appearing in the original.channels file will be because that file is later written based on those channels that were successfully parsed from the original m3u file and as far as currently behaviour goes, a channel with no group is an invalid channel so it never makes it into the successfully parsed channels collection.

**Comment by jjssoftware** [comment]
Closing on the assumption that the original question is answered to the satisfaction of the OP

**Comment by sabre6** [comment]
yes, thanks. the source has added group names for now.
