### ISSUE TITLE
[Support] question for error

### ISSUE THREAD

**Issue by sabre6** [jjssoftware/m3u-epg-editor#34]
Hi again,

My provider has rebuilt their playlist, and points to new location.  I can play the streams from the original.xml, but when i put thru the editor, i get many lines of error saying

`2019-10-08T10:48:54.123456 m3u file parse AttributeError: 'NoneType' object has no attribute 'group'`

The new .xml is much more condensed than prior and may expand, but does this indicate anything that could be overcome? Thank you.

**Comment by jjssoftware** [comment]
Hi there, this looks like an m3u parsing exception rather than it being EPG / xml related. The error is sourcing from here:

https://github.com/jjssoftware/m3u-epg-editor/blob/master/m3u-epg-editor.py#L58

This means that one or more lines in the m3u file that's being read / parsed appears to not have one of the normally present attributes:

- tvg-name
- tvg-id
- tvg-logo
- group-title

It's hard to say any more without being able to see the file but you could take a look and try and workout what's missing / where it's failing.

**Comment by sabre6** [comment]
Hi,
 
Yes, the file seems to be missing a lot.  
 
Here is a sample line – seems rather bare compared to prior ones I have seen. 
 
#EXTINF:-1   group-title="UK - Entertainment",BBC 2 HD
http://XXXXX.YYY:8080/load/##########/73551.mpegts
 
Not sure how it would work missing so much.
Thanks

**Comment by sabre6** [comment]
Thank you. Lets see if they improve the structure of the files. It might take some time.

**Comment by jjssoftware** [comment]
There's nothing more to say here other than the content of the m3u file isn't complete. Closing.
