### ISSUE TITLE
[Suggestion] Ability to Sort the Channels in XML

### ISSUE THREAD

**Issue by ap-rose** [jjssoftware/m3u-epg-editor#36]
We currently have the ability to sort channels in the m3u file but the xml is left untouched.

**Suggestion:**
Allow sort function to sort all <channel> tags in xml alphabetically or in the same order as the m3u.

**Comment by jjssoftware** [comment]
Can you please elaborate on the use-case where xml element sort order is important ?

**Comment by ap-rose** [comment]
XML Output Example
 ```
 <channel id="historychannel.ca">
    <display-name>CANADA: HISTORY</display-name>
    <icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/History_Logo.svg/225px-History_Logo.svg.png" />
  </channel>
  <channel id="global.ca">
    <display-name>CANADA: GLOBAL VANCOUVER</display-name>
    <icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Globalbc.svg/315px-Globalbc.svg.png" />
  </channel>
  <channel id="cp24.ca">
    <display-name>CANADA: CP24</display-name>
    <icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/CP24_Channel.png/225px-CP24_Channel.png" />
  </channel>
  <channel id="cbcnews.ca">
    <display-name>CANADA: CBC NEWS</display-name>
    <icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/CBC_Television_2009.svg/180px-CBC_Television_2009.svg.png" />
  </channel>
```

Be able to sort in this order
```
<channel id="cbcnews.ca"><display-name>CANADA: CBC NEWS</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/CBC_Television_2009.svg/180px-CBC_Television_2009.svg.png" /></channel>
<channel id="cp24.ca"><display-name>CANADA: CP24</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/CP24_Channel.png/225px-CP24_Channel.png" /></channel>
<channel id="global.ca"><display-name>CANADA: GLOBAL VANCOUVER</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Globalbc.svg/315px-Globalbc.svg.png" /></channel>
<channel id="historychannel.ca"><display-name>CANADA: HISTORY</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/History_Logo.svg/225px-History_Logo.svg.png" /></channel>
```

**Comment by jjssoftware** [comment]
Your last comment shows what you want to achieve but it still doesn't explain why you want to achieve this or why this is important for some use-case that you have.

If I can understand **_why_** xml element sort order is important I might agree that this is a potentially useful feature and also consider making a change that could benefit everyone. 

This isn't going to move until you can explain the motivation for this feature request in a meaningful way.

**Comment by ap-rose** [comment]
Some providers offer a sorting function for XML and dome do not.

The reason they offer the sorting function for the XML is because most android apps sort channels on their guide with the use of the XML and not the M3U.

The <programe> tags do not need sorting, only <channel> tags.

I understand that the data can be manipulated once outputted just figured this would be a neat feature as it's offered for the m3u.

Simply a Suggestion

**Comment by jjssoftware** [comment]
Thank you for clarifying.

If applications can sometimes use the sort order of channel element id values within the EPG xml file rather than using the sort order of the tvg-name values within the lines of the m3u file for sorting channels, this sounds like a reasonable feature request.

I think it's worth pointing out that if the order of channel elements in the resulting EPG xml were to follow the order of the configured `--sortchannels, -s` channels in the m3u, there is no guarantee that the channel xml elements will be in exactly the correct desired order. Here's why: 

The `--sortchannels, -s` argument currently applies to the tvg-name attribute in the m3u file and the id attribute in the channel xml element is effectively the tvg-id attribute value in the m3u. Following the m3u tvg-name order for the channel xml element id order might work well enough in most cases but perhaps not too well in others. How well that works will depend on how closely tvg-name values correlate to tvg-id values.

I don't think that there's any way around this without introducing a brand new `--sort_ids, -si` argument. If that existed it would enable the exact channel XML element id order to be specified / configured but without going that far at this stage, I'm going to propose a compromise: introduction of a new `--xml_sort_type, -xs` argument which will support the following values: None (the existing behaviour), Alphabetical, M3U. If the M3U option is used we accept that the sort order of channel elements in the resulting EPG xml may not be in exactly the desired order.

How does this sound?

**Comment by ap-rose** [comment]
Yes `--xml_sort_type` would allow for much more functionality. Looking forward to future updates !

**Comment by jjssoftware** [comment]
There's a new branch containing the candidate change: 
https://github.com/jjssoftware/m3u-epg-editor/tree/xml_sort

The newly introduced `--xml_sort_type, -xs` argument supports the following values:
- alpha,
- m3u

Give this version a try and let me know how it goes:
https://github.com/jjssoftware/m3u-epg-editor/blob/xml_sort/m3u-epg-editor.py

**Comment by ap-rose** [comment]
I will give it a try once I am back home, Sorry for the delay!

**Comment by jjssoftware** [comment]
Merged to master
