### ISSUE TITLE
Not keeping channels with blank tvg-id despite being in a kept group

### ISSUE THREAD

**Issue by geezer500** [jjssoftware/m3u-epg-editor#9]
Hi,

Thanks for a great script, I'm finding it very useful for trimming down unwanted channels.

However I noticed that some channels were missing after parsing despite the fact they were in a "kept" group...

On comparison of the input & output .m3u I could see that the missing channels had a blank tag (in the input file)...

namely the "tvg-id" tag.

i.e:

(Kept channel)
#EXTINF:-1 **tvg-id="sportsboxoffice.uk"** tvg-name="PPV: 1 (Live During Events Only)" tvg-logo="https://xxx.xx/xxx.png" group-title="PPV Events",PPV: 1 (Live During Events Only)
http://xxx.xx:80/xxx/xxx/xxx/xxx.ts

(Missing Channel)
#EXTINF:-1 **tvg-id=""** tvg-name="PPV: Fight Pass" tvg-logo="https://xxx.xx/i/xxx.png" group-title="PPV Events",PPV: Fight Pass
http://xxx.xx:80/live/xxxx/xxx/xxx.ts

I realize that the incomplete tags are probably the fault of my IPTV provider but is there any way around this? so that I may keep all the channels within the group...

Thanks

**Comment by jjssoftware** [comment]
Hi there,

This is expected behaviour for the script as it stands at the moment in this repo. The reason a decision was made to ignore channels with an empty / non-present tvg-id attribute is that it's the tvg-id that correlates channels in the m3u to channel data in the EPG file; tldr; this script is only interested in channels with EPG data.

If you want to change this behaviour you could fork and remove this line:

https://github.com/jjssoftware/m3u-epg-editor/blob/master/m3u-epg-editor.py#L266

Hope that helps

**Comment by jobrien2001** [comment]
Ill leave this here just to help the OP, i run the following command previous:

 sed -i -e 's/tvg-id=""/tvg-id="none"/g' /myfolder/myplaylist.m3u8

**Comment by geezer500** [comment]
Thanks for that!
Both ways work equally well!.
Just for the record I'm using NecroIPTV and this scripts does a great job of stripping out the cruft!
Once again, jjssoftware, thanks for the script...

**Comment by jjssoftware** [comment]
No problem thanks for the update, I'll add NecroIPTV to the list of supported / tested IPTV providers in the [readme](https://github.com/jjssoftware/m3u-epg-editor/blob/master/README.md)
